#!/bin/sh
# gen-ca-certs.sh -- regenerate src/ca_certs.h from a trusted local store.
#
# Run on macOS (reads the system root keychain). On Linux, point PEM_SOURCE at
# /etc/ssl/certs/ca-certificates.crt and adjust the extraction, or download from
# https://www.amazontrust.com/repository/ .
#
# Usage: tools/gen-ca-certs.sh > src/ca_certs.h
set -e

KEYCHAIN=/System/Library/Keychains/SystemRootCertificates.keychain
ROOTS="Amazon Root CA 1
Amazon Root CA 2
Amazon Root CA 3
Amazon Root CA 4
Starfield Services Root Certificate Authority - G2"

cat <<'HDR'
// ca_certs.h -- trust anchors, compiled into the binary.
//
// GENERATED by tools/gen-ca-certs.sh -- do not edit by hand.
//
// haiku/arm64 has no system CA store and no way to install one (NOTES.md 1,
// open question 3), so the agent ships its own. Scope is deliberately narrow:
// the Amazon Trust Services roots that ssm.* and ec2messages.* chain to.
// As of 2026-08-20, ssm.us-west-2.amazonaws.com serves:
//     CN=ssm.us-west-2.amazonaws.com
//       <- CN=Amazon RSA 2048 M04
//       <- CN=Amazon Root CA 1
// All five roots are included so a rotation to an ECDSA chain (CA 3/4) or the
// legacy cross-signed Starfield path does not break the agent in the field.
#pragma once

namespace ca {

inline const char* kAmazonTrustRoots = R"PEM(
HDR

echo "$ROOTS" | while IFS= read -r name; do
    [ -n "$name" ] || continue
    echo "# $name"
    security find-certificate -a -c "$name" -p "$KEYCHAIN"
done

cat <<'FTR'
)PEM";

}  // namespace ca
FTR
